export const CATEGORIES_ACTION_TYPES = {
    FETECH_CATEGORIES_START: 'category/FETECH_CATEGORIES_START',
    FETECH_CATEGORIES_SUCCESS: 'category/FETECH_CATEGORIES_SUCCESS',
    FETECH_CATEGORIES_FAILED: 'category/FETECH_CATEGORIES_FAILED',
}